[format]
version = '2.0'
model = 'Antminer S9'
generator = 'BOSer (boser-openwrt 0.1.0-26ba61b9)'
timestamp = 1742831464

[temp_control]
hot_temp = 100.0
dangerous_temp = 105.0

[fan_control]
min_fans = 2

[[group]]
name = 'Default'

[[group.pool]]
enabled = true
url = 'stratum2+tcp://v2.stratum.braiins.com/u95GEReVMjK6k5YqiSFNqqTnKU4ypU2Wm8awa6tmbmDmk1bWt'
user = 'bitofreedom.{hostname}'
password = 'x'

[[group.pool]]
enabled = true
url = 'stratum+tcp://sha256asicboost.auto.nicehash.com:9200'
user = '3DCT5e1xtDWhYPicATxgk5a5FRF6GhZDfH.{hostname}'
password = 'x'

[autotuning]
enabled = true
power_target = 1100

[performance_scaling]
enabled = false